spring:
  application:
    name: Desktop-Fairy
  profiles:
    include:
      - api
      - log
      - datasource
      - prompt
      - mp
      - filepath



server:
  port: 18765
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
