spring:
  application:
    name: Desktop-Fairy
  main:
    lazy-initialization: true
  profiles:
    include:
      - api
      - log
      - datasource
      - prompt
      - mp
      - filepath



server:
  address: 127.0.0.1
  port: 18765
  servlet:
    context-path: /api
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  error:
    include-stacktrace: NEVER
    include-exception: false