export const customText = {
  composer: {
    selectModel: '选择模型配置',
    noModels: '当前无可选模型',
    filterModelsPlaceholder: '筛选模型配置',
    noFilteredModels: '没有匹配的模型配置',
  },
  session: {
    create: '新建对话',
    searchPlaceholder: '搜索会话',
    settingsHint: '打开设置',
  },
  settings: {
    title: '设置',
    backToApp: '返回应用',
    placeholderStatus: '设置模块',
  },
  modelSource: {
    listTitle: '供应商配置',
    detailFallbackTitle: '供应商',
    listStatus: '供应商配置',
    detailStatus: '编辑供应商',
    createTitle: '新建',
    createTooltip: '新建供应商',
    backToListTitle: '返回列表',
    testPending: '测试中',
    testIdle: '未测试',
    providerPlaceholder: '选择或输入 provider',
    providerFilterPlaceholder: '筛选 provider',
    providerNoMatch: '没有匹配的 provider',
    localInstallTitle: '安装本地测试模型',
    localStartTitle: '启动本地测试模型',
    localStopTitle: '停止本地测试模型',
    localViewLogTitle: '查看日志',
    localHideLogTitle: '收起日志',
    localStdoutTitle: '标准输出',
    localStderrTitle: '错误输出',
    localExitCodeLabel: '退出码',
    localScriptLabel: '脚本',
    localInstallSuccess: '本地测试模型已安装并添加到模型源',
    localRunning: '本地服务运行中',
    localStopped: '本地服务已停止',
    localErrorFallback: '本地测试模型操作失败',
  },
  chatPreferences: {
    title: '运行参数',
    status: '聊天参数',
    resetTitle: '恢复默认',
    defaultsTitle: '默认参数',
    defaultsDescription: '发送消息时自动带入，留空则由后端使用默认值。',
    summaryTitle: '当前生效',
    summaryDescription: '这里只保存前端工作台使用的运行参数。',
    emptyHint: '当前未设置自定义运行参数。',
    temperatureLabel: 'Temperature',
    maxTokensLabel: 'Max Tokens',
    defaultPlaceholder: '默认',
  },
  appearance: {
    title: '界面外观',
    status: '界面外观',
    globalFontTitle: '全局字体',
    globalFontDescription: '开启后使用 Source Han Serif CN 作为全局字体。',
    globalFontToggleTitle: '切换全局字体',
    themeTitle: '页面主题',
    themeDescription: '切换页面颜色风格，仅影响前端外观显示。',
    lightTheme: '亮色模式',
    darkTheme: '夜间模式',
    jetbrainsTheme: 'JetBrains 风格',
  },
  runtimePopover: {
    title: '模型参数',
    temperatureLabel: 'Temperature',
    maxTokensLabel: 'Max Tokens',
    defaultPlaceholder: '默认',
  },
} as const;
