export const customText = {
  composer: {
    selectModel: '选择模型配置',
    noModels: '当前无可选模型',
    filterModelsPlaceholder: '筛选模型配置',
    noFilteredModels: '没有匹配的模型配置',
  },
  session: {
    create: '新建对话',
    searchPlaceholder: '搜索会话',
    settingsHint: '打开设置',
  },
  settings: {
    title: '设置',
    backToApp: '返回应用',
    placeholderStatus: '设置模块',
  },
  modelSource: {
    listTitle: '供应商配置',
    detailFallbackTitle: '供应商',
    listStatus: '供应商配置',
    detailStatus: '编辑供应商',
    createTitle: '新建',
    createTooltip: '新建供应商',
    backToListTitle: '返回列表',
    testPending: '测试中',
    testIdle: '未测试',
    providerPlaceholder: '选择或输入 provider',
    providerFilterPlaceholder: '筛选 provider',
    providerNoMatch: '没有匹配的 provider',
    localInstallTitle: '安装本地测试模型',
    localStartTitle: '启动本地测试模型',
    localStopTitle: '停止本地测试模型',
    localViewLogTitle: '查看日志',
    localHideLogTitle: '收起日志',
    localStdoutTitle: '标准输出',
    localStderrTitle: '错误输出',
    localExitCodeLabel: '退出码',
    localScriptLabel: '脚本',
    localInstallConfirmStatus: '本地测试模型安装确认',
    localInstallConfirmTitle: '安装 Qwen3.5-4B-UD-IQ2_XXS',
    localInstallConfirmDescription: '将安装并尝试启动本地测试模型 Qwen3.5-4B-UD-IQ2_XXS，成功后自动写入本地供应商配置。',
    localInstallConfirmPythonNotice: '当前不会自动安装 Python。本机如果未安装 Python 或未正确加入 PATH，脚本会直接中断，请先自行安装 Python 运行环境。',
    localInstallConfirmDependencyNotice: '除 Python 外，其余运行所需依赖会由脚本自行检查并按需安装，包括 huggingface_hub、llama.cpp 或 llama-server，以及模型文件本身。',
    localInstallConfirmManualHint: '如果你已经自行下载并启动本地模型，也可以按 OpenAI 兼容方式手动新增供应商配置：baseUrl 填本地服务地址，apiKey 可留空，但建议统一填写 local。',
    localInstallConfirmDurationHint: '首次下载和启动受网络与磁盘速度影响较大，通常需要 10 到 30 分钟。安装期间请不要重复点击安装。',
    localInstallConfirmCancel: '取消',
    localInstallConfirmSubmit: '确定安装',
    localInstallSuccess: '本地测试模型已安装并添加到模型源',
    localRunning: '本地服务运行中',
    localStopped: '本地服务已停止',
    localErrorFallback: '本地测试模型操作失败',
  },
  chatPreferences: {
    title: '运行参数',
    status: '聊天参数',
    resetTitle: '恢复默认',
    defaultsTitle: '默认参数',
    defaultsDescription: '发送消息时自动带入，留空则使用默认值。',
    summaryTitle: '当前生效',
    summaryDescription: '这里只保存工作台使用的运行参数。',
    emptyHint: '当前未设置自定义运行参数。',
    temperatureLabel: 'Temperature',
    maxTokensLabel: 'Max Tokens',
    systemPromptLabel: 'System Prompt',
    systemPromptPlaceholder: '默认提示词： you are a helpful assistant',
    defaultPlaceholder: '默认',
  },
  appearance: {
    title: '界面外观',
    status: '界面外观',
    globalFontTitle: '全局字体',
    globalFontDescription: '开启后使用 Source Han Serif CN 作为全局字体。',
    globalFontToggleTitle: '切换全局字体',
    themeTitle: '页面主题',
    themeDescription: '切换页面颜色风格，仅影响前端外观显示。',
    lightTheme: '亮色模式',
    darkTheme: '夜间模式',
    jetbrainsTheme: 'JetBrains',
  },
  desktopBehavior: {
    title: '桌面行为',
    status: '桌面精灵',
    enableTitle: '启用桌面精灵',
    enableDescription: '开启后会显示独立的桌面精灵窗口，与主工作台分离运行。',
    enableToggleTitle: '切换桌面精灵显示状态',
    residentChatTitle: '常驻闲聊模式',
    residentChatDescription: '开启后会为桌面精灵预留常驻闲聊能力，后续可在用户主动进入或长时间闲置时自动触发临时闲聊回复。此功能可能带来额外 token 消耗，默认关闭。',
    residentChatToggleTitle: '切换常驻闲聊模式',
    residentChatEnabledTag: '常驻闲聊已开启',
    residentChatDisabledTag: '常驻闲聊未开启',
    sizeTitle: '显示大小',
    sizeDescription: '调节独立桌面精灵窗口中的角色显示大小，并自动保存设置。',
    sizeLabel: '当前缩放',
    resetScaleTitle: '恢复默认大小',
    resetScaleButton: '重置大小',
    positionTitle: '悬浮位置',
    positionDescription: '独立桌面精灵窗口支持单独拖拽移动，当前位置会自动记忆。',
    positionTag: '当前位置',
    positionDefaultTag: '当前位置使用默认右下角',
    resetPositionTitle: '重置为默认位置',
    resetPositionButton: '重置位置',
    actionsTitle: '快捷操作',
    actionsDescription: '可快速恢复推荐显示大小与默认悬浮位置。',
    visibleTag: '悬浮显示中',
    hiddenTag: '悬浮已关闭',
  },
  runtimePopover: {
    title: '模型参数',
    temperatureLabel: 'Temperature',
    maxTokensLabel: 'Max Tokens',
    defaultPlaceholder: '默认',
  },
} as const;
