import type { ErrorType, ToolStage } from '@/types/chat';

export const uiText = {
  composer: {
    placeholder: '输入消息，Enter 发送，Shift + Enter 换行',
    addAttachment: '添加附件',
    settings: '模型与 API 设置',
    rollback: '回退最后一轮并回填输入框',
    stop: '停止',
    send: '发送',
    voiceUnsupported: '当前浏览器不支持语音输入',
    voicePreparing: '正在准备语音识别...',
    voiceStop: '点击停止语音输入',
    voiceStart: '点击开始语音输入（首次使用需下载模型）',
    toolCallOn: '已开启工具调用',
    toolCallOff: '开启工具调用',
  },
  toolCall: {
    summary: '工具调用',
    entry: '第 {round} 轮',
    expand: '查看完整工具调用过程',
    collapse: '收起',
    stages: {
      LOOP_START: '工具循环开始',
      ROUND_START: '轮次开始',
      TOOL_CALL: '检测到工具调用',
      ROUND_CONTINUE: '进入下一轮',
      ROUND_FINISH: '模型已结束本轮',
      ROUND_LIMIT: '达到最大轮次',
      TOOL_LIMIT: '达到工具调用上限',
      TIME_LIMIT: '达到执行时长上限',
      TOOL_RESULT: '工具结果',
      MEDIA_REQUEST_START: '正在获取图片并等待模型处理',
    } satisfies Record<ToolStage, string>,
  },
  session: {
    operations: '会话操作',
    rename: '重命名',
    delete: '删除会话',
    renamePrompt: '请输入新的会话标题',
    deleteConfirm: (title: string) => `确认删除会话「${title}」及其历史记录？`,
  },
  chat: {
    emptyMessage: '当前会话暂无消息，可以直接开始提问。',
    pullMore: '下拉加载更多历史消息',
    releaseToLoad: '释放加载更多历史消息',
    loadingHistory: '正在加载历史消息...',
    noMoreHistory: '没有更多历史消息',
    reasoningPending: '思考中...',
    reasoningLoading: '模型正在整理思路...',
    reasoningEmpty: '本轮没有返回可展示的思考内容。',
    speakerUser: 'you',
    speakerAssistant: 'assistant',
    viewReasoning: '查看思考内容',
    copy: '复制',
    copied: '已复制',
    rollbackLatestRound: '回退并回填输入框',
    deleteLatestRound: '删除最后一轮',
    refreshHistory: '重新拉取当前会话历史',
    historyRefreshed: '历史已刷新',
    backToBottom: '回到底部',
    untitledSession: '未选择会话',
  },
  messageStatus: {
    completed: '已完成',
    interrupted: '已中断',
    error: '异常',
    sending: '发送中',
    streaming: '生成中',
  },
  errors: {
    initFailed: '初始化失败',
    refreshHistoryFailed: '刷新历史失败',
    createSessionFailed: '创建会话失败',
    loadHistoryFailed: '历史消息加载失败',
    sendFailed: '发送失败',
    streamUnsupported: '当前环境不支持读取流式响应',
    requestFailed: '请求失败',
    modelRequired: '请先选择模型配置后再发送消息',
    // 1005 错误事件 errorType 对应的中文标签
    errorTypes: {
      UNAUTHORIZED: '认证失败',
      FORBIDDEN: '拒绝访问',
      NOT_FOUND: '地址不可用',
      RATE_LIMIT: '请求频率受限',
      INSUFFICIENT_BALANCE: '额度不足',
      TIMEOUT: '响应超时',
      CONNECTION_RESET: '连接中断',
      CONNECTION_FAILED: '连接失败',
      SERVER_ERROR: '服务不可用',
      BAD_REQUEST: '请求参数异常',
      UNKNOWN: '未知错误',
    } satisfies Record<ErrorType, string>,
    retry: '重试',
    partialOutputHint: '以上内容可能不完整',
  },
  backend: {
    connecting: '正在连接后端服务...',
    connectingHint: '首次启动需要等待几秒钟，后端准备就绪后将自动恢复',
    reconnecting: '后端连接已断开',
    reconnectingHint: '正在尝试重新连接后端服务，请稍候...',
  },
} as const;
