export const uiText = {
  composer: {
    placeholder: '输入消息，Enter 发送，Shift + Enter 换行',
    addAttachment: '添加附件',
    settings: '模型与 API 设置',
    rollback: '回退最后一轮并回填输入框',
    stop: '停止',
    send: '发送',
  },
  session: {
    operations: '会话操作',
    rename: '重命名',
    delete: '删除会话',
    renamePrompt: '请输入新的会话标题',
    deleteConfirm: (title: string) => `确认删除会话「${title}」及其历史记录？`,
  },
  chat: {
    emptyMessage: '当前会话暂无消息，可以直接开始提问。',
    pullMore: '下拉加载更多历史消息',
    releaseToLoad: '释放加载更多历史消息',
    loadingHistory: '正在加载历史消息...',
    noMoreHistory: '没有更多历史消息',
    reasoningPending: '思考中...',
    reasoningLoading: '模型正在整理思路...',
    reasoningEmpty: '本轮没有返回可展示的思考内容。',
    speakerUser: 'you',
    speakerAssistant: 'assistant',
    viewReasoning: '查看思考内容',
    copy: '复制',
    rollbackLatestRound: '回退并回填输入框',
    deleteLatestRound: '删除最后一轮',
    refreshHistory: '重新拉取当前会话历史',
    backToBottom: '回到底部',
    untitledSession: '未选择会话',
  },
  messageStatus: {
    completed: '已完成',
    interrupted: '已中断',
    error: '异常',
    sending: '发送中',
    streaming: '生成中',
  },
  errors: {
    initFailed: '初始化失败',
    refreshHistoryFailed: '刷新历史失败',
    loadHistoryFailed: '历史消息加载失败',
    sendFailed: '发送失败',
    streamUnsupported: '当前环境不支持读取流式响应',
    requestFailed: '请求失败',
    modelRequired: '请先选择模型配置后再发送消息',
  },
} as const;
